# Form implementation generated from reading ui file 'qt_creator_files/Ui_DiceRollerWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DiceRollerWindow(object):
    def setupUi(self, DiceRollerWindow):
        DiceRollerWindow.setObjectName("DiceRollerWindow")
        DiceRollerWindow.resize(1287, 691)
        self.centralwidget = QtWidgets.QWidget(parent=DiceRollerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sheet_tab_widget = QtWidgets.QTabWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.sheet_tab_widget.sizePolicy().hasHeightForWidth()
        )
        self.sheet_tab_widget.setSizePolicy(sizePolicy)
        self.sheet_tab_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.sheet_tab_widget.setTabsClosable(True)
        self.sheet_tab_widget.setMovable(True)
        self.sheet_tab_widget.setObjectName("sheet_tab_widget")
        self.home_tab = QtWidgets.QWidget()
        self.home_tab.setObjectName("home_tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.home_tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.homes_sheet = HomeSheetWidget(parent=self.home_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.homes_sheet.sizePolicy().hasHeightForWidth())
        self.homes_sheet.setSizePolicy(sizePolicy)
        self.homes_sheet.setMinimumSize(QtCore.QSize(1000, 600))
        self.homes_sheet.setStyleSheet("")
        self.homes_sheet.setObjectName("homes_sheet")
        self.horizontalLayout_2.addWidget(self.homes_sheet)
        self.sheet_tab_widget.addTab(self.home_tab, "")
        self.horizontalLayout.addWidget(self.sheet_tab_widget)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(
            20,
            30,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Fixed,
        )
        self.verticalLayout_2.addItem(spacerItem)
        self.cmd_terminal = QtWidgets.QTextBrowser(parent=self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmd_terminal.sizePolicy().hasHeightForWidth())
        self.cmd_terminal.setSizePolicy(sizePolicy)
        self.cmd_terminal.setObjectName("cmd_terminal")
        self.verticalLayout_2.addWidget(self.cmd_terminal)
        self.cmd_input = QtWidgets.QLineEdit(parent=self.widget_2)
        self.cmd_input.setStyleSheet("")
        self.cmd_input.setObjectName("cmd_input")
        self.verticalLayout_2.addWidget(self.cmd_input)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.horizontalLayout.addWidget(self.widget)
        DiceRollerWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=DiceRollerWindow)
        self.statusbar.setObjectName("statusbar")
        DiceRollerWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(parent=DiceRollerWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1287, 17))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuWindow = QtWidgets.QMenu(parent=self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuSheet = QtWidgets.QMenu(parent=self.menubar)
        self.menuSheet.setObjectName("menuSheet")
        self.menuCard = QtWidgets.QMenu(parent=self.menubar)
        self.menuCard.setObjectName("menuCard")
        DiceRollerWindow.setMenuBar(self.menubar)
        self.action_open_readme = QtGui.QAction(parent=DiceRollerWindow)
        self.action_open_readme.setObjectName("action_open_readme")
        self.actionHome_Tab = QtGui.QAction(parent=DiceRollerWindow)
        self.actionHome_Tab.setObjectName("actionHome_Tab")
        self.actionOpen_current_sheet_in_new_window = QtGui.QAction(
            parent=DiceRollerWindow
        )
        self.actionOpen_current_sheet_in_new_window.setObjectName(
            "actionOpen_current_sheet_in_new_window"
        )
        self.action_move_window_to_new = QtGui.QAction(parent=DiceRollerWindow)
        self.action_move_window_to_new.setObjectName("action_move_window_to_new")
        self.action_show_home_sheet = QtGui.QAction(parent=DiceRollerWindow)
        self.action_show_home_sheet.setObjectName("action_show_home_sheet")
        self.actionOpen = QtGui.QAction(parent=DiceRollerWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.action_new_sheet = QtGui.QAction(parent=DiceRollerWindow)
        self.action_new_sheet.setObjectName("action_new_sheet")
        self.actionOpen_in_new_window = QtGui.QAction(parent=DiceRollerWindow)
        self.actionOpen_in_new_window.setObjectName("actionOpen_in_new_window")
        self.actionOpen_folder = QtGui.QAction(parent=DiceRollerWindow)
        self.actionOpen_folder.setObjectName("actionOpen_folder")
        self.action_open_sheet = QtGui.QAction(parent=DiceRollerWindow)
        self.action_open_sheet.setObjectName("action_open_sheet")
        self.action_open_folder = QtGui.QAction(parent=DiceRollerWindow)
        self.action_open_folder.setObjectName("action_open_folder")
        self.actionValues = QtGui.QAction(parent=DiceRollerWindow)
        self.actionValues.setObjectName("actionValues")
        self.actionNotes = QtGui.QAction(parent=DiceRollerWindow)
        self.actionNotes.setObjectName("actionNotes")
        self.action_new_sheet_2 = QtGui.QAction(parent=DiceRollerWindow)
        self.action_new_sheet_2.setObjectName("action_new_sheet_2")
        self.action_open_sheet_2 = QtGui.QAction(parent=DiceRollerWindow)
        self.action_open_sheet_2.setObjectName("action_open_sheet_2")
        self.action_open_values = QtGui.QAction(parent=DiceRollerWindow)
        self.action_open_values.setObjectName("action_open_values")
        self.action_open_notes = QtGui.QAction(parent=DiceRollerWindow)
        self.action_open_notes.setObjectName("action_open_notes")
        self.action_save_sheet = QtGui.QAction(parent=DiceRollerWindow)
        self.action_save_sheet.setObjectName("action_save_sheet")
        self.action_add_card = QtGui.QAction(parent=DiceRollerWindow)
        self.action_add_card.setObjectName("action_add_card")
        self.action_open_sheet_3 = QtGui.QAction(parent=DiceRollerWindow)
        self.action_open_sheet_3.setObjectName("action_open_sheet_3")
        self.action_new_sheet_3 = QtGui.QAction(parent=DiceRollerWindow)
        self.action_new_sheet_3.setObjectName("action_new_sheet_3")
        self.action_save_sheet_2 = QtGui.QAction(parent=DiceRollerWindow)
        self.action_save_sheet_2.setObjectName("action_save_sheet_2")
        self.action_open_stats = QtGui.QAction(parent=DiceRollerWindow)
        self.action_open_stats.setObjectName("action_open_stats")
        self.action_open_notes_2 = QtGui.QAction(parent=DiceRollerWindow)
        self.action_open_notes_2.setObjectName("action_open_notes_2")
        self.action_add_cards = QtGui.QAction(parent=DiceRollerWindow)
        self.action_add_cards.setObjectName("action_add_cards")
        self.menuHelp.addAction(self.action_open_readme)
        self.menuWindow.addAction(self.action_move_window_to_new)
        self.menuWindow.addAction(self.action_show_home_sheet)
        self.menuSheet.addAction(self.action_open_sheet_3)
        self.menuSheet.addAction(self.action_new_sheet_3)
        self.menuSheet.addAction(self.action_save_sheet_2)
        self.menuCard.addAction(self.action_open_stats)
        self.menuCard.addAction(self.action_open_notes_2)
        self.menuCard.addAction(self.action_add_cards)
        self.menubar.addAction(self.menuSheet.menuAction())
        self.menubar.addAction(self.menuCard.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(DiceRollerWindow)
        self.sheet_tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DiceRollerWindow)

    def retranslateUi(self, DiceRollerWindow):
        _translate = QtCore.QCoreApplication.translate
        DiceRollerWindow.setWindowTitle(
            _translate("DiceRollerWindow", "Marcus's Dice Roller")
        )
        self.sheet_tab_widget.setTabText(
            self.sheet_tab_widget.indexOf(self.home_tab),
            _translate("DiceRollerWindow", "Home"),
        )
        self.menuHelp.setTitle(_translate("DiceRollerWindow", "Help"))
        self.menuWindow.setTitle(_translate("DiceRollerWindow", "Window"))
        self.menuSheet.setTitle(_translate("DiceRollerWindow", "Sheet"))
        self.menuCard.setTitle(_translate("DiceRollerWindow", "Cards"))
        self.action_open_readme.setText(_translate("DiceRollerWindow", "README"))
        self.actionHome_Tab.setText(_translate("DiceRollerWindow", "Show Home sheet"))
        self.actionOpen_current_sheet_in_new_window.setText(
            _translate("DiceRollerWindow", "Open current sheet in new window")
        )
        self.action_move_window_to_new.setText(
            _translate("DiceRollerWindow", "Move current sheet to new window")
        )
        self.action_show_home_sheet.setText(
            _translate("DiceRollerWindow", "Show home sheet")
        )
        self.actionOpen.setText(_translate("DiceRollerWindow", "Open sheet"))
        self.action_new_sheet.setText(_translate("DiceRollerWindow", "Add Card"))
        self.actionOpen_in_new_window.setText(
            _translate("DiceRollerWindow", "Open in new window")
        )
        self.actionOpen_folder.setText(_translate("DiceRollerWindow", "Open folder"))
        self.action_open_sheet.setText(_translate("DiceRollerWindow", "Sheet"))
        self.action_open_folder.setText(_translate("DiceRollerWindow", "Folder"))
        self.actionValues.setText(_translate("DiceRollerWindow", "Values"))
        self.actionNotes.setText(_translate("DiceRollerWindow", "Notes"))
        self.action_new_sheet_2.setText(_translate("DiceRollerWindow", "New Sheet"))
        self.action_open_sheet_2.setText(_translate("DiceRollerWindow", "Open Sheet"))
        self.action_open_values.setText(_translate("DiceRollerWindow", "Values"))
        self.action_open_notes.setText(_translate("DiceRollerWindow", "Notes"))
        self.action_save_sheet.setText(_translate("DiceRollerWindow", "Save Sheet"))
        self.action_add_card.setText(_translate("DiceRollerWindow", "Add Card"))
        self.action_open_sheet_3.setText(_translate("DiceRollerWindow", "Open Sheet"))
        self.action_new_sheet_3.setText(_translate("DiceRollerWindow", "New Sheet"))
        self.action_save_sheet_2.setText(_translate("DiceRollerWindow", "Save Sheet"))
        self.action_open_stats.setText(_translate("DiceRollerWindow", "Stats"))
        self.action_open_notes_2.setText(_translate("DiceRollerWindow", "Notes"))
        self.action_add_cards.setText(_translate("DiceRollerWindow", "Add Cards"))


from src.view.HomeSheetWidget import HomeSheetWidget
