# Form implementation generated from reading ui file 'qt_creator_files/Ui_HomeSheet.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_HomeSheet(object):
    def setupUi(self, HomeSheet):
        HomeSheet.setObjectName("HomeSheet")
        HomeSheet.resize(1000, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(HomeSheet.sizePolicy().hasHeightForWidth())
        HomeSheet.setSizePolicy(sizePolicy)
        HomeSheet.setMinimumSize(QtCore.QSize(1000, 600))
        self.horizontalLayout = QtWidgets.QHBoxLayout(HomeSheet)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=HomeSheet)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.recent_sheets_list = QtWidgets.QListWidget(parent=HomeSheet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recent_sheets_list.sizePolicy().hasHeightForWidth())
        self.recent_sheets_list.setSizePolicy(sizePolicy)
        self.recent_sheets_list.setObjectName("recent_sheets_list")
        self.verticalLayout.addWidget(self.recent_sheets_list)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=HomeSheet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)

        self.retranslateUi(HomeSheet)
        QtCore.QMetaObject.connectSlotsByName(HomeSheet)

    def retranslateUi(self, HomeSheet):
        _translate = QtCore.QCoreApplication.translate
        HomeSheet.setWindowTitle(_translate("HomeSheet", "Form"))
        self.label.setText(_translate("HomeSheet", "Recent Sheets"))
        self.label_2.setText(_translate("HomeSheet", " Welcome to Marcus\'s Dice Roller"))
