# Form implementation generated from reading ui file 'qt_creator_files/Ui_NoteCardConfig.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NoteCardConfig(object):
    def setupUi(self, NoteCardConfig):
        NoteCardConfig.setObjectName("NoteCardConfig")
        NoteCardConfig.resize(234, 106)
        self.formLayout = QtWidgets.QFormLayout(NoteCardConfig)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=NoteCardConfig)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.note_combo_box = QtWidgets.QComboBox(parent=NoteCardConfig)
        self.note_combo_box.setObjectName("note_combo_box")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.note_combo_box)
        self.label_2 = QtWidgets.QLabel(parent=NoteCardConfig)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.column_spin_box = QtWidgets.QSpinBox(parent=NoteCardConfig)
        self.column_spin_box.setMinimum(1)
        self.column_spin_box.setProperty("value", 2)
        self.column_spin_box.setObjectName("column_spin_box")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.column_spin_box)
        self.label_3 = QtWidgets.QLabel(parent=NoteCardConfig)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.row_spin_box = QtWidgets.QSpinBox(parent=NoteCardConfig)
        self.row_spin_box.setMinimum(1)
        self.row_spin_box.setProperty("value", 2)
        self.row_spin_box.setObjectName("row_spin_box")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.row_spin_box)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=NoteCardConfig)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.buttonBox)

        self.retranslateUi(NoteCardConfig)
        self.buttonBox.accepted.connect(NoteCardConfig.accept) # type: ignore
        self.buttonBox.rejected.connect(NoteCardConfig.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(NoteCardConfig)

    def retranslateUi(self, NoteCardConfig):
        _translate = QtCore.QCoreApplication.translate
        NoteCardConfig.setWindowTitle(_translate("NoteCardConfig", "Dialog"))
        self.label.setText(_translate("NoteCardConfig", "Note"))
        self.label_2.setText(_translate("NoteCardConfig", "Column Span"))
        self.label_3.setText(_translate("NoteCardConfig", "Row Span"))
