# Form implementation generated from reading ui file 'qt_creator_files/Ui_NoteEditor.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NoteEditor(object):
    def setupUi(self, NoteEditor):
        NoteEditor.setObjectName("NoteEditor")
        NoteEditor.resize(800, 500)
        self.gridLayout = QtWidgets.QGridLayout(NoteEditor)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=NoteEditor)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=NoteEditor)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.note_list_view = QtWidgets.QListView(parent=NoteEditor)
        self.note_list_view.setObjectName("note_list_view")
        self.gridLayout.addWidget(self.note_list_view, 1, 0, 1, 1)
        self.line = QtWidgets.QFrame(parent=NoteEditor)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 1, 1, 1)
        self.history_text_edit = QtWidgets.QTextEdit(parent=NoteEditor)
        self.history_text_edit.setObjectName("history_text_edit")
        self.gridLayout.addWidget(self.history_text_edit, 1, 2, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=NoteEditor)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 3, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setColumnStretch(3, 2)

        self.retranslateUi(NoteEditor)
        self.buttonBox.accepted.connect(NoteEditor.accept) # type: ignore
        self.buttonBox.rejected.connect(NoteEditor.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(NoteEditor)

    def retranslateUi(self, NoteEditor):
        _translate = QtCore.QCoreApplication.translate
        NoteEditor.setWindowTitle(_translate("NoteEditor", "Dialog"))
        self.label.setText(_translate("NoteEditor", "Notes"))
        self.label_2.setText(_translate("NoteEditor", "TextLabel"))
