# Form implementation generated from reading ui file 'qt_creator_files/Ui_StatCardConfig.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_StatCardConfig(object):
    def setupUi(self, StatCardConfig):
        StatCardConfig.setObjectName("StatCardConfig")
        StatCardConfig.resize(800, 500)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(StatCardConfig)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=StatCardConfig)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.stat_list_view = QtWidgets.QListView(parent=StatCardConfig)
        self.stat_list_view.setObjectName("stat_list_view")
        self.verticalLayout_2.addWidget(self.stat_list_view)
        self.label_2 = QtWidgets.QLabel(parent=StatCardConfig)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.order_up_button = QtWidgets.QPushButton(parent=StatCardConfig)
        self.order_up_button.setObjectName("order_up_button")
        self.verticalLayout_2.addWidget(self.order_up_button)
        self.order_down_button = QtWidgets.QPushButton(parent=StatCardConfig)
        self.order_down_button.setObjectName("order_down_button")
        self.verticalLayout_2.addWidget(self.order_down_button)
        spacerItem = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.delete_button = QtWidgets.QPushButton(parent=StatCardConfig)
        self.delete_button.setObjectName("delete_button")
        self.verticalLayout_2.addWidget(self.delete_button)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.line = QtWidgets.QFrame(parent=StatCardConfig)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(parent=StatCardConfig)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.card_config_stat_table_view = QtWidgets.QTableView(parent=StatCardConfig)
        self.card_config_stat_table_view.setObjectName("card_config_stat_view")
        self.verticalLayout.addWidget(self.card_config_stat_table_view)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(2, 3)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=StatCardConfig)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(StatCardConfig)
        self.buttonBox.accepted.connect(StatCardConfig.accept) # type: ignore
        self.buttonBox.rejected.connect(StatCardConfig.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(StatCardConfig)

    def retranslateUi(self, StatCardConfig):
        _translate = QtCore.QCoreApplication.translate
        StatCardConfig.setWindowTitle(_translate("StatCardConfig", "Dialog"))
        self.label.setText(_translate("StatCardConfig", "Add Stats"))
        self.label_2.setText(_translate("StatCardConfig", "Edit Stats"))
        self.order_up_button.setText(_translate("StatCardConfig", "↑"))
        self.order_down_button.setText(_translate("StatCardConfig", "↓"))
        self.delete_button.setText(_translate("StatCardConfig", "Delete"))
        self.label_3.setText(_translate("StatCardConfig", "Configure Card"))
