# Form implementation generated from reading ui file 'qt_creator_files/Ui_StatEditor.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_StatEditor(object):
    def setupUi(self, StatEditor):
        StatEditor.setObjectName("StatEditor")
        StatEditor.resize(800, 500)
        self.gridLayout = QtWidgets.QGridLayout(StatEditor)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=StatEditor)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(parent=StatEditor)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 1, 2, 1)
        self.label_2 = QtWidgets.QLabel(parent=StatEditor)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.stat_table_view = QtWidgets.QTableView(parent=StatEditor)
        self.stat_table_view.setObjectName("stat_table_view")
        self.gridLayout.addWidget(self.stat_table_view, 1, 0, 1, 1)
        self.history_table_view = QtWidgets.QTableView(parent=StatEditor)
        self.history_table_view.setObjectName("history_table_view")
        self.gridLayout.addWidget(self.history_table_view, 1, 2, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=StatEditor)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 2, 1, 1)

        self.retranslateUi(StatEditor)
        self.buttonBox.accepted.connect(StatEditor.accept) # type: ignore
        self.buttonBox.rejected.connect(StatEditor.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(StatEditor)

    def retranslateUi(self, StatEditor):
        _translate = QtCore.QCoreApplication.translate
        StatEditor.setWindowTitle(_translate("StatEditor", "Dialog"))
        self.label.setText(_translate("StatEditor", "Stats"))
        self.label_2.setText(_translate("StatEditor", "Stat History"))
